services:

  fastapi:
    build: .
    container_name: fastapi-container
    ports:
      - "8000:8000"

  postgres:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: shrutika
      POSTGRES_PASSWORD: shrutika123
      POSTGRES_DB: hybriddb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: mongodb-container
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  neo4j:
    image: neo4j:5
    container_name: neo4j-container
    environment:
      NEO4J_AUTH: neo4j/password123
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

volumes:
  postgres_data:
  mongo_data:
  neo4j_data:
